site_name: Sistemas Informáticos
site_author: Carlos Mestre Ferrández
site_description: Guía didáctica del módulo de Sistemas Informáticos - 1º DAW
theme:
  name: material  
  palette:
    primary: blue
    accent: indigo
  language: es
  features:
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.expand
    - content.code.copy
    - content.action.edit
    - content.action.view
    - toc.integrate
    - search.suggest
    - search.highlight
  favicon: img/favicon.ico
  logo: img/favicon.png
nav:
  - Resumen del módulo: index.md
  - Unidad 1: unidad1.md
  - Unidad 2: unidad2.md
  - Unidad 3: unidad3.md
  - Unidad 4: unidad4.md
  - Unidad 5: unidad5.md
  - Unidad 6: unidad6.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: cards
          class: cards
          format: !!python/name:pymdownx.superfences.fence_div_format
  - pymdownx.highlight
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji
  - toc:
      permalink: true
  - attr_list
  - md_in_html

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://cmestref.github.io/sistemas_informaticos/
      name: GitHub

plugins:
  - search

extra_css:
  - stylesheets/extra.css