site_name: Sistemas Informáticos
theme:
  name: material
nav:
  - Inicio: index.md
  - Unidad 1: unidad1.md
  - Unidad 2: unidad2.md
  - Unidad 3: unidad3.md
  - Unidad 4: unidad4.md
  - Unidad 5: unidad5.md
  - Unidad 6: unidad6.md
